# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('soyad', models.CharField(max_length=20)),
                ('tc', models.CharField(max_length=11)),
                ('silah', models.CharField(max_length=100)),
                ('rutbe', models.CharField(max_length=100)),
                ('seri', models.CharField(max_length=12)),
                ('publicing_date', models.DateTimeField()),
            ],
        ),
    ]
