# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='soyad',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
