# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190702_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rutbe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='seri',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='silah',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tc',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
