# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190702_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('serial', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='images/personel')),
            ],
        ),
        migrations.CreateModel(
            name='GunBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GunStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Gun')),
            ],
        ),
        migrations.CreateModel(
            name='GunType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('image', models.ImageField(upload_to='images/personel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('rank_order', models.IntegerField(default=0)),
                ('logo', models.ImageField(upload_to='images/rank')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('rank_order', models.IntegerField(default=0)),
                ('logo', models.ImageField(upload_to='images/rank')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostType',
        ),
        migrations.AddField(
            model_name='personel',
            name='personel_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.PersonelClass'),
        ),
        migrations.AddField(
            model_name='personel',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Rank'),
        ),
        migrations.AddField(
            model_name='gunstorage',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Personel'),
        ),
        migrations.AddField(
            model_name='gun',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.GunBrand'),
        ),
        migrations.AddField(
            model_name='gun',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.GunType'),
        ),
    ]
